services:
  firestore-emulator:
    image: google/cloud-sdk:emulators
    platform: linux/amd64 # Specify platform explicitly
    ports:
      - "8081:8081"
    environment:
      - FIRESTORE_PROJECT_ID=demo-project
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8081
    command: >
      gcloud beta emulators firestore start
      --host-port=0.0.0.0:8081
      --project=demo-project
